---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: memcached
  labels:
    project: mcrouter-memcached
    role: memcached-server
    app: memcached
spec:
  replicas: 2
  selector:
    matchLabels:
      project: mcrouter-memcached
      role: memcached-server
      app: memcached
  template:
    metadata:
      labels:
        project: mcrouter-memcached
        role: memcached-server
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.4-alpine
        env:
        - name: CLUSTER_ROLE
          value: "memcached"
        ports:
        - containerPort: 11211
---
# This creates a headless service that allows us to look up all memcached instances via k8s DNS
#
# i.e.
# `nslookup memcached-service`
kind: Service
apiVersion: v1
metadata:
  name: memcached-service
  labels:
    project: mcrouter-memcached
    role: memcached-server
    app: memcached
spec:
  type: ClusterIP
  clusterIP: 
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
  selector:
    project: mcrouter-memcached
    role: memcached-server
    app: memcached
